#!/bin/sh

DAEMON="psplash"
PIDFILE="/var/run/$DAEMON.pid"

start() {
    printf "Starting %s: " "$DAEMON"
    start-stop-daemon --start --background --make-pidfile \
        --pidfile "$PIDFILE" --exec "/usr/bin/$DAEMON"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping %s: " "$DAEMON"
    start-stop-daemon --stop --pidfile "$PIDFILE" --exec "/usr/bin/$DAEMON"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    rm -f "$PIDFILE"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?