#!/bin/sh

start() {
    printf "Finishing psplash: "
    for pid in $(pidof psplash); do
        kill -QUIT "$pid"
    done
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start|stop|restart|reload)
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?